#!/usr/bin/python

"""
PyBal
Copyright (C) 2006 by Mark Bergsma <mark@nedworks.org>

LVS Squid balancer/monitor for managing the Wikimedia Squid servers using LVS
"""

from pybal import main

if __name__ == '__main__':
    main.main()
